version: 1.0-{build}

os:
  - Visual Studio 2015

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - mkdir build
  - cd build
  - ..\nmake-dll.bat
  - ..\nmake-lib.bat

after_build:
  - 7z a keystone-windows.zip build\llvm\bin\keystone.dll
  - 7z a keystone-windows.zip build\llvm\lib\keystone.lib
  - 7z a keystone-windows.zip build\kstool\kstool.exe

artifacts:
  - path: keystone-windows.zip
    name: keystone-windows.zip

  - path: build\llvm\bin\keystone.dll
    name: keystone.dll

  - path: build\llvm\lib\keystone.lib
    name: keystone.lib

  - path: build\kstool\kstool.exe
    name: kstool.exe
