version: 1.0-{build}

os:
  - Visual Studio 2015

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - mkdir build
  - cd build
  - ..\nmake-dll.bat
  - ..\nmake-lib.bat

artifacts:
  - path: build\llvm\bin\keystone.dll
    name: keystone.dll
	type: zip

  - path: build\llvm\lib\keystone.lib
    name: keystone.lib
	type: zip

  - path: build\kstool\kstool.exe
    name: kstool.exe
	type: zip
