version: 1.0-{build}

os:
  - Visual Studio 2015

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - mkdir build
  - cd build
  - ..\nmake-dll.bat
  - ..\nmake-lib.bat

