version: 1.0-{build}

os:
  - Visual Studio 2015

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - mkdir build
  - cd build
  - ..\nmake-dll.bat
  - ..\nmake-lib.bat

after_build:
  - mkdir zip
  - copy llvm\bin\keystone.dll zip
  - copy llvm\lib\keystone.lib zip
  - copy kstool\kstool.exe zip
  - 7z a keystone-windows-latest.zip zip\*

artifacts:
  - path: build\keystone-windows-latest.zip
    name: keystone-windows-latest.zip

  - path: build\llvm\bin\keystone.dll
    name: keystone.dll

  - path: build\llvm\lib\keystone.lib
    name: keystone.lib

  - path: build\kstool\kstool.exe
    name: kstool.exe
